[package]
name = "geckodriver"
version = "0.22.0"
description = "Proxy for using WebDriver clients to interact with Gecko-based browsers."
keywords = ["webdriver", "w3c", "httpd", "mozilla", "firefox"]
repository = "https://hg.mozilla.org/mozilla-central/file/tip/testing/geckodriver"
readme = "README.md"
license = "MPL-2.0"
publish = false

[dependencies]
base64 = "0.9"
chrono = "^0.2"
clap = { version = "^2.19", default-features = false, features = ["suggestions", "wrap_help"] }
hyper = "0.12"
lazy_static = "1.0"
log = { version = "0.4", features = ["std"] }
mozprofile = "0.4.0"
mozrunner = "0.8"
mozversion = "0.1.3"
regex = "1.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
uuid = { version = "0.5", features = ["v4"] }
webdriver = "0.37"
zip = "0.3"

[[bin]]
name = "geckodriver"
